language: python
python:
  - 3.8
services:
  - postgresql
addons:
  postgresql: '12.4'

install:
  - pip install -q pipenv codecov
  - pipenv sync --dev

script:
  - pipenv run flake8 .
  - pipenv run pytest --cov=curso

after_success:
  - pipenv run codecov